### PR TITLE
update quantization configurations for ryzenai (vai_q_onnx)

### PR DESCRIPTION
**Pull request by ChaoLi-AMD**

### CODE REVIEW

**Comment by mht-sharma** [comment]
Hi @ChaoLi-AMD  is this the final changes agreed in the meeting?

**Comment by ChaoLi-AMD** [comment]
> Hi @ChaoLi-AMD is this the final changes agreed in the meeting?

This is the first step discussed in the meeting, where we changed the enum to a string. There will be further alignment in the future.

**Comment by Giuseppe5** [comment]
Looks good to me!

**Comment by ChaoLi-AMD** [comment]
Hi Mohit, is this PR ready to be merged? @mht-sharma

**Review by mht-sharma — APPROVED** [review]
Sorry for the delay @ChaoLi-AMD . This LGTM.

**Pull request merged**
